#!/usr/bin/env bash

response=$(curl --silent --show-error --fail -X GET 'https://pokeapi.co/api/v2/pokemon/' 2>&1)

status=$?
if [ $status -ne 0 ]; then
    echo "Failed with error code: $status" > errors.txt
else 
    echo "$response" > data.json
fi
