#!/usr/bin/env bash

API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

curl -s -o "$OUTPUT_FILE" -w "%{http_code}" "$API_URL" | {
    read HTTP_STATUS
    
    if [ "$HTTP_STATUS" -eq 200 ]; then
        echo "Data successfully saved to $OUTPUT_FILE"
    else 
        echo "Error: Failed to fetch data. HTTP Status: $status" >> errors.txt
    fi
}
